apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-storage-volume
spec:
  storageClassName: "prom"
  capacity:
    storage: 20G
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: monitoring 
    name: pv-claim-prom
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/birmingham-302418/zones/us-central1-c/disks/prometheus-storage-volume
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: pv-claim-prom
spec:
  storageClassName: "prom"
  volumeName: prometheus-storage-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20G

